Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
print("hello")

hello


In [4]:
import pandas as pd
import numpy as np

In [5]:
my_dict = {"james" : 50,"lars" : 60, "kirk" : 55, "rob" : 65}


In [6]:
pd.Series(my_dict)

james    50
lars     60
kirk     55
rob      65
dtype: int64

In [7]:
age_list = [50,60,55,65]
name_list = ["james","lars","kirk","rob"] 

In [8]:
pd.Series(name_list,age_list)

50    james
60     lars
55     kirk
65      rob
dtype: object

In [9]:
pd.Series(data=age_list,index=name_list)

james    50
lars     60
kirk     55
rob      65
dtype: int64

In [10]:
numpy_array = np.arange(0,8)

In [11]:
numpy_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
pd.Series(numpy_array)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int32

In [13]:
new_numpy_array = np.array([10,20,30,40])

In [14]:
pd.Series(new_numpy_array)

0    10
1    20
2    30
3    40
dtype: int32

In [15]:
new_numpy_array

array([10, 20, 30, 40])

In [16]:
name_list

['james', 'lars', 'kirk', 'rob']

In [17]:
pd.Series(data=new_numpy_array,index=name_list)

james    10
lars     20
kirk     30
rob      40
dtype: int32

In [19]:
my_series = pd.Series(data=new_numpy_array,index=name_list)

In [20]:
my_series

james    10
lars     20
kirk     30
rob      40
dtype: int32

In [21]:
type(my_series)

pandas.core.series.Series

In [22]:
my_series["kirk"] 

30

In [23]:
my_series["kirk"] = 60

In [24]:
my_series["kirk"]

60

In [25]:
quiz_results1 = pd.Series([10,20,30],["a","b","c"])

In [26]:
quiz_results2 = pd.Series([70,80,90],["a","b","c"])

In [27]:
quiz_results1

a    10
b    20
c    30
dtype: int64

In [28]:
quiz_results2


a    70
b    80
c    90
dtype: int64

In [30]:
quiz_results1 + quiz_results2

a     80
b    100
c    120
dtype: int64

In [31]:
exam_results = pd.Series([10,20,30],["a","b","c"])
exam_results2 = pd.Series([10,20,30],["a","d","c"])

In [32]:
exam_results+exam_results2

a    20.0
b     NaN
c    60.0
d     NaN
dtype: float64

In [33]:
my_data = np.array([[10,20,30],[20,30,40],[20,50,10],[10,15,20]])

In [34]:
my_data

array([[10, 20, 30],
       [20, 30, 40],
       [20, 50, 10],
       [10, 15, 20]])

In [35]:
my_names = ["james","lars","kirk","rob"]
my_columbs = ["jan","feb","mar"]

In [36]:
my_data_frame = pd.DataFrame(my_data)

In [37]:
my_data_frame

0   1   2
0  10  20  30
1  20  30  40
2  20  50  10
3  10  15  20

In [38]:
type(my_data_frame)

pandas.core.frame.DataFrame

In [39]:
my_data_frame[1]

0    20
1    30
2    50
3    15
Name: 1, dtype: int32

In [43]:
new_data_frame = pd.DataFrame(my_data, index = my_names,columns = my_columbs)

In [44]:
new_data_frame

jan  feb  mar
james   10   20   30
lars    20   30   40
kirk    20   50   10
rob     10   15   20

In [45]:
new_data_frame["feb"]

james    20
lars     30
kirk     50
rob      15
Name: feb, dtype: int32

In [46]:
type(new_data_frame["feb"])

pandas.core.series.Series

In [47]:
feb_series = new_data_frame["feb"]

In [48]:
feb_series.mean()

28.75

In [53]:
feb_series.lars

30

In [54]:
new_data_frame["jan"].mean()

15.0

In [55]:
new_data_frame[["jan","feb"]]

jan  feb
james   10   20
lars    20   30
kirk    20   50
rob     10   15

In [56]:
new_data_frame.loc["lars"]

jan    20
feb    30
mar    40
Name: lars, dtype: int32

In [57]:
type(new_data_frame.loc["lars"])

pandas.core.series.Series

In [58]:
new_data_frame.loc["rob"].mean()

15.0

In [59]:
new_data_frame

jan  feb  mar
james   10   20   30
lars    20   30   40
kirk    20   50   10
rob     10   15   20

In [60]:
new_data_frame.iloc[3]

jan    10
feb    15
mar    20
Name: rob, dtype: int32

In [61]:
new_data_frame["apr"] = new_data_frame["mar"]*2

In [62]:
new_data_frame

jan  feb  mar  apr
james   10   20   30   60
lars    20   30   40   80
kirk    20   50   10   20
rob     10   15   20   40

In [63]:
new_data_frame.drop("rob",axis=0)
#orjinallik bozulmuyor

jan  feb  mar  apr
james   10   20   30   60
lars    20   30   40   80
kirk    20   50   10   20

In [64]:
new_data_frame

jan  feb  mar  apr
james   10   20   30   60
lars    20   30   40   80
kirk    20   50   10   20
rob     10   15   20   40

In [66]:
new_data_frame.drop("apr",axis=1)
#axis=0 satır,axis=1  kolon demek

jan  feb  mar
james   10   20   30
lars    20   30   40
kirk    20   50   10
rob     10   15   20

In [69]:
 new_data_frame.drop("kirk",axis=0)
    #orjinal hala aynı

jan  feb  mar  apr
james   10   20   30   60
lars    20   30   40   80
rob     10   15   20   40

In [70]:
new_data_frame.drop("apr",axis=1,inplace = True)

In [71]:
new_data_frame

jan  feb  mar
james   10   20   30
lars    20   30   40
kirk    20   50   10
rob     10   15   20

In [72]:
new_data_frame["jan"].lars

20

In [73]:
new_data_frame["mar"]["james"]

30

In [74]:
boolean_frame = new_data_frame > 25

In [75]:
boolean_frame

jan    feb    mar
james  False  False   True
lars   False   True   True
kirk   False   True  False
rob    False  False  False

In [76]:
new_data_frame[boolean_frame]
# new_data_frame[new_data_frame > 30] aynı şey

jan   feb   mar
james  NaN   NaN  30.0
lars   NaN  30.0  40.0
kirk   NaN  50.0   NaN
rob    NaN   NaN   NaN

In [78]:
new_data_frame[new_data_frame["mar"]>25]

jan  feb  mar
james   10   20   30
lars    20   30   40

In [79]:
new_data_frame.reset_index()

index  jan  feb  mar
0  james   10   20   30
1   lars   20   30   40
2   kirk   20   50   10
3    rob   10   15   20

In [80]:
new_data_frame

jan  feb  mar
james   10   20   30
lars    20   30   40
kirk    20   50   10
rob     10   15   20

In [81]:
new_data_frame["newindex"] = ["jam","lar","kir","robert"]

In [82]:
new_data_frame

jan  feb  mar newindex
james   10   20   30      jam
lars    20   30   40      lar
kirk    20   50   10      kir
rob     10   15   20   robert

In [84]:
new_data_frame.set_index("newindex")

jan  feb  mar
newindex               
jam        10   20   30
lar        20   30   40
kir        20   50   10
robert     10   15   20

In [85]:
new_data_frame

jan  feb  mar newindex
james   10   20   30      jam
lars    20   30   40      lar
kirk    20   50   10      kir
rob     10   15   20   robert

In [87]:
new_data_frame.drop("newindex",axis = 1,inplace=True)

In [88]:
new_data_frame

jan  feb  mar
james   10   20   30
lars    20   30   40
kirk    20   50   10
rob     10   15   20

In [98]:
my_dicti = {"james":[40,30,np.nan],"kikr":[20,np.nan,50],"lars":[30,40,50]}

In [99]:
my_data_framee = pd.DataFrame(my_dicti)

In [100]:
my_data_framee

james  kikr  lars
0   40.0  20.0    30
1   30.0   NaN    40
2    NaN  50.0    50

In [101]:
my_data_framee.dropna()

james  kikr  lars
0   40.0  20.0    30

In [102]:
my_data_framee

james  kikr  lars
0   40.0  20.0    30
1   30.0   NaN    40
2    NaN  50.0    50

In [103]:
my_data_framee.dropna(axis = 1)

lars
0    30
1    40
2    50

In [104]:
my_new_dicti = {"james":[40,30,np.nan],"kikr":[20,np.nan,50],"lars":[30,40,50],"rob":[45,np.nan,np.nan]}

In [105]:
my_neww_frame = pd.DataFrame(my_new_dicti) 

In [106]:
my_neww_frame

james  kikr  lars   rob
0   40.0  20.0    30  45.0
1   30.0   NaN    40   NaN
2    NaN  50.0    50   NaN

In [107]:
my_neww_frame.dropna(axis = 1,thresh=2)
#min seviye

james  kikr  lars
0   40.0  20.0    30
1   30.0   NaN    40
2    NaN  50.0    50

In [108]:
my_neww_frame.dropna(axis = 1,thresh=3)
#min seviye

lars
0    30
1    40
2    50

In [109]:
my_neww_frame.dropna(axis = 1,thresh=4)
#min seviye

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [110]:
my_neww_frame.fillna(20)

james  kikr  lars   rob
0   40.0  20.0    30  45.0
1   30.0  20.0    40  20.0
2   20.0  50.0    50  20.0

In [114]:
salary_dict = {"programmin language" : ["python","python","python","swift","java","java"],"name":["a","b","c","d","e","f"],"salary" : [100,90,80,70,60,50]}

In [115]:
salary_frame = pd.DataFrame(salary_dict)

In [116]:
salary_frame

programmin language name  salary
0              python    a     100
1              python    b      90
2              python    c      80
3               swift    d      70
4                java    e      60
5                java    f      50

In [135]:
group_object = salary_frame.groupby("programmin language")
group_object1 = salary_frame.groupby("salary")

In [136]:
group_object.count()

name  salary
programmin language              
java                    2       2
python                  3       3
swift                   1       1

In [138]:
group_object.min()

name  salary
programmin language             
java                   e      50
python                 a      80
swift                  d      70

In [139]:
group_object.max()
#her iki sutunda da mini getirdiği için yanlış harfli olanları getirdi.

name  salary
programmin language             
java                   f      60
python                 c     100
swift                  d      70

In [140]:
group_object

salary
programmin language        
java                     50
python                   80
swift                    70

In [141]:
group_object.max("salary")

salary
programmin language        
java                     60
python                  100
swift                    70

In [142]:
group_object.min(numeric_only=True)

salary
programmin language        
java                     50
python                   80
swift                    70

In [143]:
group_object.describe()

salary                                                
                     count  mean        std   min   25%   50%   75%    max
programmin language                                                       
java                   2.0  55.0   7.071068  50.0  52.5  55.0  57.5   60.0
python                 3.0  90.0  10.000000  80.0  85.0  90.0  95.0  100.0
swift                  1.0  70.0        NaN  70.0  70.0  70.0  70.0   70.0

In [144]:
my_dict1 = {"name": ["a","b","c","d"],
           "sport":["basket","futbol","tenis","koşu"],
           "calories":[100,200,300,400]}

In [164]:
my_frame1=pd.DataFrame(my_dict1)

In [165]:
my_frame1

name   sport  calories
0    a  basket       100
1    b  futbol       200
2    c   tenis       300
3    d    koşu       400

In [166]:
my_dict2 = {"name": ["e","f","g","h"],
           "sport":["basket","futbol","tenis","koşu"],
           "calories":[200,50,330,440]}

In [167]:
my_frame2 = pd.DataFrame(my_dict2, index = [4,5,6,7])

In [168]:
my_frame2

name   sport  calories
4    e  basket       200
5    f  futbol        50
6    g   tenis       330
7    h    koşu       440

In [169]:
my_dict3 = {"name": ["i","j","k","l"],
           "sport":["basket","futbol","tenis","koşu"],
           "calories":[300,150,320,410]}

In [170]:
my_frame3 = pd.DataFrame(my_dict3,index = [8,9,10,11])

In [171]:
my_frame3

name   sport  calories
8     i  basket       300
9     j  futbol       150
10    k   tenis       320
11    l    koşu       410

In [172]:
#concat

In [173]:
pd.concat([my_frame1,my_frame2,my_frame3])

name   sport  calories
0     a  basket       100
1     b  futbol       200
2     c   tenis       300
3     d    koşu       400
4     e  basket       200
5     f  futbol        50
6     g   tenis       330
7     h    koşu       440
8     i  basket       300
9     j  futbol       150
10    k   tenis       320
11    l    koşu       410

In [174]:
#merge

In [178]:
pd.merge(my_frame1,my_frame2,on="sport")

name_x   sport  calories_x name_y  calories_y
0      a  basket         100      e         200
1      b  futbol         200      f          50
2      c   tenis         300      g         330
3      d    koşu         400      h         440

In [179]:
new_salary_frame = pd.DataFrame({"name" : ["james","kirk","lars"],"salary":[10,20,30],"age":[60,65,70]})

In [180]:
new_salary_frame

name  salary  age
0  james      10   60
1   kirk      20   65
2   lars      30   70

In [181]:
new_salary_frame["name"].unique()

array(['james', 'kirk', 'lars'], dtype=object)

In [182]:
new_salary_frame["name"].nunique()

3

In [187]:
def grosstonet(salary):
    return salary * 0.65

In [189]:
new_salary_frame["salary"].apply(grosstonet)

0     6.5
1    13.0
2    19.5
Name: salary, dtype: float64